---
# This file can be used to be added to the opencloud_full example
# to browse the LDAP server with a web interface.
# This is not a production ready setup.
services:
  ldap-manager:
    image: phpldapadmin/phpldapadmin:latest
    networks:
      opencloud-net:
    environment:
      LDAP_HOST: ldap-server
      LDAP_PORT: 1389
      LDAP_LOGIN_OBJECTCLASS: "inetOrgPerson"
      APP_URL: "https://${LDAP_MANAGER_DOMAIN:-ldap.opencloud.test}"
    ports:
      - "8080:8080"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
